# Generated by Django 5.1.1 on 2024-10-01 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_comment_parent_delete_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('id', '-id')},
        ),
    ]
